<?php

define("ENV_DIR", realpath( __DIR__.'/../../' ) );

$dotenv = Dotenv\Dotenv::createImmutable( ENV_DIR );
$dotenv->load();
$dotenv->required([
  'BSKY_API_APP_NAME',
  'BSKY_API_APP_USER',
  'BSKY_API_APP_TOKEN',
  'MASTODON_API_APP_TOKEN',
  'MASTODON_API_APP_URL',
  'INSTANCE_SOCIAL_USER',
  'INSTANCE_SOCIAL_APPNAME',
  'INSTANCE_SOCIAL_APPID',
  'INSTANCE_SOCIAL_TOKEN'
]);

//define("MASTODON_ACCOUNT_ID", $_ENV['MASTODON_ACCOUNT_ID'] );
define("MASTODON_API_APP_TOKEN", $_ENV['MASTODON_API_APP_TOKEN'] );
define("MASTODON_API_APP_URL", $_ENV['MASTODON_API_APP_URL'] );

define("MASTODON_API_CRAWLER_URL", $_ENV['MASTODON_API_CRAWLER_URL'] );
define("MASTODON_API_CRAWLER_TOKEN", $_ENV['MASTODON_API_CRAWLER_TOKEN'] );

define("BSKY_API_APP_USER", $_ENV['BSKY_API_APP_USER']);
define("BSKY_API_APP_TOKEN", $_ENV['BSKY_API_APP_TOKEN']);

define("INSTANCE_SOCIAL_TOKEN", $_ENV['INSTANCE_SOCIAL_TOKEN']);

if( isset( $_ENV['LINGUA_CLI'] ) )
  define("LINGUA_CLI", $_ENV['LINGUA_CLI'] );

if( isset( $_ENV['GNUPLOT_CLI'] ) )
  define("GNUPLOT_CLI", $_ENV['GNUPLOT_CLI'] );

define("INDEX_CACHE_DIR", ENV_DIR."/cache");

unset( $_ENV['MASTODON_API_TOKEN'] );

if( isset( $_ENV['DEBUG'] ) ) {

  echo "MASTODON_API_APP_URL : ".MASTODON_API_APP_URL."\n";
  echo "INDEX_CACHE_DIR  : ".INDEX_CACHE_DIR."\n";

}
